### ISSUE TITLE
Missing apiwin32

### ISSUE THREAD

**Issue by phoenixml** [ersaurabhverma/autoplotter#3]
Hi thank you for sharing this awesome tool,
i am trying to use autoplotter on collab, however it is asking for missing module apiwin32
I installed pypiwin32 but also an error is occurring as showing below:
"Error cannot find a version that satisfies the requirement"

I also uploaded pywin32_postinstall.py after installing it is displaying the same error.

I tried to install via python2.7 and Python3 same problem any feedback/ solution would be appreciated.
Thank you 😊

**Comment by ersaurabhverma** [comment]
Try 
pip install pywin32

**Comment by cassidythilton** [comment]
I have the same issue. pip install pywin32 does not remediate.

**Comment by ersaurabhverma** [comment]
I will update the package ASAP. 
It might because you have linux machine.

**Comment by aspotter99** [comment]
I am having the same issue on a Mac

**Comment by phoenixml** [comment]
Thank you @ersaurabhverma I will be awaiting for the updated package cheers for your that 🙌🏻

**Comment by Buckler89** [comment]
+1 for linux support. 
I think a lot of people and online notebook are running on linux.

**Comment by Santanu7** [comment]
Please make it compatible for linux. Thank you. Let me know if I can help in any way.

**Comment by thelittlebug** [comment]
the idea: "i want to get the browser width with an call to an win32 (or in future linux/macos) api on the serverside" is just wrong.
thats not how it could work in any possible way.

just set the WIDTH to "100%" in app.py and you are done.
no platform depended code.

**Comment by thelittlebug** [comment]
pull requests: https://github.com/ersaurabhverma/autoplotter/pull/4

**Comment by thelittlebug** [comment]
if you need a quickfix
```
pip uninstall autoplotter
pip install git+git://github.com/thelittlebug/autoplotter

**Comment by ersaurabhverma** [comment]
I have updated the package and removed the dependency on win32api.
