### ISSUE TITLE
Key Error while trying to Explore data- Support for date type column will be good

### ISSUE THREAD

**Issue by techwithshadab** [ersaurabhverma/autoplotter#6]
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
//anaconda3/lib/python3.7/site-packages/plotly/express/_core.py in make_trace_kwargs(
    args={'animation_frame': None, 'animation_group': None, 'barmode': 'relative', 'barnorm': None, 'category_orders': {}, 'color': None, 'color_discrete_map': {}, 'color_discrete_sequence': ['tomato'], 'cumulative': None, 'data_frame':               F1        F2        F3        F4  ...66000903 1979-07-27  

[101180 rows x 15 columns], ...},
    trace_spec=TraceSpec(constructor=<class 'plotly.graph_objs....a'], trace_patch={'notched': True}, marginal='x'),
    trace_data=              F1        F2        F3        F4  ...66000903 1979-07-27  

[101180 rows x 15 columns],
    mapping_labels=OrderedDict([('F1', '%{customdata[0]}'), ('F2', ...customdata[12]}'), ('F14', '%{customdata[13]}')]),
    sizeref=0
)
    294                         try:
--> 295                             position = args["custom_data"].index(col)
        position = 14
        args.index = undefined
        col = 'F15'
    296                         except (ValueError, AttributeError, KeyError):

KeyError: 'custom_data'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
//anaconda3/lib/python3.7/site-packages/plotly/express/_core.py in make_trace_kwargs(
    args={'animation_frame': None, 'animation_group': None, 'barmode': 'relative', 'barnorm': None, 'category_orders': {}, 'color': None, 'color_discrete_map': {}, 'color_discrete_sequence': ['tomato'], 'cumulative': None, 'data_frame':               F1        F2        F3        F4  ...66000903 1979-07-27
```

**Comment by hafez-ahmad** [comment]
from autoplotter import run_app 
AttributeError                            Traceback (most recent call last)
<ipython-input-4-28a14e47e46d> in <module>
----> 1 from autoplotter import run_app

c:\users\hafez\miniconda3\lib\site-packages\autoplotter\__init__.py in <module>
----> 1 from .app import run_app
      2 
      3 __ALL__ = ['run_app']

c:\users\hafez\miniconda3\lib\site-packages\autoplotter\app.py in <module>
      8 from .homepage import homepage
      9 from collections import OrderedDict
---> 10 from .plots_layout import plot_layout,plot_graph, add_parameters, _params, add_layer
     11 from .data_exploration import dataexploration, plot_distributions, association
     12 

c:\users\hafez\miniconda3\lib\site-packages\autoplotter\plots_layout.py in <module>
      2 import dash_html_components as html
      3 import dash_core_components as dcc
----> 4 import plotly.express as px
      5 import plotly.graph_objects as go
      6 import logging

c:\users\hafez\miniconda3\lib\site-packages\plotly\express\__init__.py in <module>
     13     )
     14 
---> 15 from ._imshow import imshow
     16 from ._chart_types import (  # noqa: F401
     17     scatter,

c:\users\hafez\miniconda3\lib\site-packages\plotly\express\_imshow.py in <module>
      5 
      6 try:
----> 7     import xarray
      8 
      9     xarray_imported = True

c:\users\hafez\miniconda3\lib\site-packages\xarray\__init__.py in <module>
      1 import pkg_resources
      2 
----> 3 from . import testing, tutorial, ufuncs
      4 from .backends.api import (
      5     load_dataarray,

c:\users\hafez\miniconda3\lib\site-packages\xarray\tutorial.py in <module>
     12 import numpy as np
     13 
---> 14 from .backends.api import open_dataset as _open_dataset
     15 from .core.dataarray import DataArray
     16 from .core.dataset import Dataset

c:\users\hafez\miniconda3\lib\site-packages\xarray\backends\__init__.py in <module>
      4 formats. They should not be used directly, but rather through Dataset objects.
      5 """
----> 6 from .cfgrib_ import CfGribDataStore
      7 from .common import AbstractDataStore
      8 from .file_manager import CachingFileManager, DummyFileManager, FileManager

c:\users\hafez\miniconda3\lib\site-packages\xarray\backends\cfgrib_.py in <module>
      5 from ..core.variable import Variable
      6 from .common import AbstractDataStore, BackendArray
----> 7 from .locks import SerializableLock, ensure_lock
      8 
      9 # FIXME: Add a dedicated lock, even if ecCodes is supposed to be thread-safe

c:\users\hafez\miniconda3\lib\site-packages\xarray\backends\locks.py in <module>
     11 
     12 try:
---> 13     from dask.distributed import Lock as DistributedLock
     14 except ImportError:
     15     DistributedLock = None

c:\users\hafez\miniconda3\lib\site-packages\dask\distributed.py in <module>
      3 
      4 try:
----> 5     from distributed import *
      6 except ImportError:
      7     msg = ("Dask's distributed scheduler is not installed.\n\n"

c:\users\hafez\miniconda3\lib\site-packages\distributed\__init__.py in <module>
----> 1 from . import config
      2 from dask.config import config
      3 from .actor import Actor, ActorFuture
      4 from .core import connect, rpc
      5 from .deploy import LocalCluster, Adaptive, SpecCluster, SSHCluster

c:\users\hafez\miniconda3\lib\site-packages\distributed\config.py in <module>
      9 from .compatibility import logging_names
     10 
---> 11 config = dask.config.config
     12 
     13 

AttributeError: module 'dask' has no attribute 'config'

**Comment by hafez-ahmad** [comment]
I solved it by uninstalling the dask.

**Comment by ersaurabhverma** [comment]
That's great so I am closing this thread.
