### ISSUE TITLE
The example usage code won't execute

### ISSUE THREAD

**Issue by RafeyIqbalRahman** [ersaurabhverma/autoplotter#8]
So, I did a `!pip install pywin32` to successfully execute `!pip install autoplotter` on my Windows machine with Python 3.7 which worked fine. But when I executed the example usage, I got the ModuleNotFound Error for win32api. As @thelittlebug mentioned in #3, you should set the width to 100% to overcomplicate. 

Here's some extra tip for you:

I see that you are using GetSystemMetrics in app.py which is not optimal. The reason being that GetSysyemMetrics is not DPI-aware and does not support per-monitor DPI-awareness. Per-monitor DPI-aware means that your laptop or PC has an external display. The DPI for both, the laptop and the external screen, will be different. This is why DPI-aware is optimal. Fortunately, there's a DPI-aware version of this API available by the name of GetSystemMetricsforDPI, perhaps this will help you in your future projects.

**Comment by ersaurabhverma** [comment]
I have updated the package and removed the win32api dependency.
So, I am closing this issue.
